### ISSUE TITLE
Problems to authenticate using openldap

### ISSUE THREAD

**Issue by viniciusrsdutra** [dpgaspar/Flask-AppBuilder#321] opened 2016-05-09 15:18 UTC
Hi everyone!
I'm new to Caravel and made the necessary changes to bind to LDAP. I'm using OpenLDAP.
According to the app log the changes are ok, but users can't login at the front end.
Any help?

Thanks in advance
![ldap-problem](https://cloud.githubusercontent.com/assets/6311982/15117824/c2868108-15df-11e6-916f-9e8b9d4c03bb.png)
![ldap-problem](https://cloud.githubusercontent.com/assets/6311982/15086197/7961c4c8-13b5-11e6-8f3f-da51d7d75dce.png)

**Comment by dpgaspar** [comment] 2016-05-09 16:30
Can you upgrade flask-appbuilder to version 1.6.1 and run the test again, and send me logs once more?

**Comment by viniciusrsdutra** [comment] 2016-05-09 18:57
Hi @dpgaspar!
Thanks for helping!
I did as instructed but I got the same behavior...
Here follows the versions I'm using and the log after updating everything.
![image](https://cloud.githubusercontent.com/assets/6311982/15124470/99393a74-15fe-11e6-8a9c-b05eb14a5ce9.png)
![ldap-problem-3](https://cloud.githubusercontent.com/assets/6311982/15124491/b2bdff5c-15fe-11e6-8bc3-e1ce8838e521.png)

**Comment by dpgaspar** [comment] 2016-05-09 20:38
Ok, no login failed message, i'll run some tests, could you send me your config.py (AUTH_LDAP* settings).

**Comment by dpgaspar** [comment] 2016-05-09 23:53
My tests went fine with OpenLDAP::

```
2016-05-10 00:49:29,456:DEBUG:flask_appbuilder.security.manager:LDAP indirect bind with: CN=admin,dc=puppetlabs,dc=test
2016-05-10 00:49:29,458:DEBUG:flask_appbuilder.security.manager:LDAP BIND indirect OK
2016-05-10 00:49:29,459:DEBUG:flask_appbuilder.security.manager:LDAP got User [('uid=test,ou=people,dc=puppetlabs,dc=test', {'mail': ['test@example.com'], 'sn': ['User']})]
2016-05-10 00:49:29,459:DEBUG:flask_appbuilder.security.manager:LDAP bind with: uid=test,ou=people,dc=puppetlabs,dc=test XXXXXX
2016-05-10 00:49:29,460:DEBUG:flask_appbuilder.security.manager:LDAP bind OK: uid=test,ou=people,dc=puppetlabs,dc=test
2016-05-10 00:49:29,465:INFO:flask_appbuilder.security.sqla.manager:Updated user test test
2016-05-10 00:49:29,467:INFO:werkzeug:127.0.0.1 - - [10/May/2016 00:49:29] "POST /login/ HTTP/1.1" 302 -
2016-05-10 00:49:29,519:INFO:werkzeug:127.0.0.1 - - [10/May/2016 00:49:29] "GET / HTTP/1.1" 200 -
2016-05-10 00:49:32,594:INFO:werkzeug:127.0.0.1 - - [10/May/2016 00:49:32] "GET /users/list/ HTTP/1.1" 200 -
```

Looks like f.a.b. was able to catch the user vinicius.dutra@XXXX.XXXX, do you have this user registered on the database with the exact same username ?

**Comment by viniciusrsdutra** [comment] 2016-05-10 11:45
@dpgaspar, the user is properly registered on LDAP!
Here follows my LDAP config parameters for config.py
![caravel-ldap-config](https://cloud.githubusercontent.com/assets/6311982/15145359/752a3b0a-168b-11e6-99c1-d8bb38f350aa.png)

**Comment by dpgaspar** [comment] 2016-05-10 13:37
Yes, i was able to login on the UI, with test user (you saw on the logs) and other test users like 'dpgaspar'.

Can you try creating a test user without the <UID>@<SOMECENSUREDDOMAIN> just the <UID>. Try to reproduce my test case please.

**Comment by viniciusrsdutra** [comment] 2016-05-10 14:23
@dpgaspar Did it, but results were the same.
![ldap-problem-4](https://cloud.githubusercontent.com/assets/6311982/15149888/aa6e6aaa-16a1-11e6-894b-285afe5144c8.png)

**Comment by viniciusrsdutra** [comment] 2016-05-10 18:16
@dpgaspar Does the LDAP have to be configured in a way in particular?
Do you have any clue about it?

**Comment by dpgaspar** [comment] 2016-05-13 11:03
I just created a vagrant box using https://github.com/cforcey/vagrant_ubuntu_openldap
No extra config on it....

My config for tests:

AUTH_TYPE = AUTH_LDAP
AUTH_LDAP_SEARCH = 'dc=puppetlabs,dc=test'
AUTH_LDAP_BIND_USER = "CN=admin,dc=puppetlabs,dc=test"
AUTH_LDAP_BIND_PASSWORD = "test"

First of course i've added a test user on F.A.B. The only diference i can see is the AUTH_LDAP_BIND_USER, i'm using CN and your using UID. Change this, make some tests, and send me the logs, can you send something more extended? after GET /login/ HTTP ... 

You can use this for tests also:

``` python
import ldap

con = ldap.initialize("ldap://ldap-somewhere.com")
con.set_option(ldap.OPT_REFERRALS, 0)
con.bind_s('caravel@yourdomain.local', 'password')

user = con.search_s('dc=domain,dc=local',ldap.SCOPE_SUBTREE, "userPrincipalName=test@yourdomain.local",
                    ['givenName','sn','mail'])

print user[0][0]

```

**Comment by dpgaspar** [comment] 2016-05-27 14:49
Any luck?

**Comment by viniciusrsdutra** [comment] 2016-05-31 15:21
Hi @dpgaspar, 

Unfortunately I had not! Sorry for responding so late!
Tried several configs and packages but no success at all...
I've noticed that I couldn't install the python-ldap package from pip. The only one that works is the one provided by ubuntu. How's the package configuration on your vagrant environment?
Can this be the thing that is making the difference?

**Comment by viniciusrsdutra** [comment] 2016-05-31 18:07
@dpgaspar 
Thank you so much for your patience and cooperation on solving this. 
[Eric Wong](https://github.com/mtrbean) gave the [tip](https://github.com/airbnb/caravel/issues/443) that made the difference. After enabling AUTH_USER_REGISTRATION property it worked.
Many thanks once again!

**Comment by dpgaspar** [comment] 2016-06-08 17:36
Ho! i thought you had registered the user on flask-appbuilder first!

I said that "First of course i've added a test user on F.A.B.". 

I were not understanding each other :)

You've got it working, great! I'll close this one.

**Closed by dpgaspar** 2016-06-08 17:36 UTC
Labels: pending, question
