### ISSUE TITLE
Upload thing to AWS S3

### ISSUE THREAD

**Issue by Tim-Ho** [dpgaspar/Flask-AppBuilder#834] opened 2018-10-23 03:08 UTC
Hlello, dpgaspar.
I have deployed the appbuilder website on a aws EC2 and connect the website's database to the AWS RDS.
Now, I am about to play more AWS service. To load the burden of the website, I want to use AWS S3 storage to upload all static file to S3... 
How can I achieve it?
Can I use boto3? 
Or Is there any other way to achieve it?
Could you tell me in detail? Cause I am not good at absorbing and I am just a cloud beginner.
Thanks !

**Comment by MichaelPereira** [comment] 2018-10-23 03:46
Yes, this kind of integration would be achieved through the use of boto3, most likely only "using" resources like existing S3 buckets, not managing their lifecycle (creation/destruction) as this would be quite out of scope of this project and better handled by dedicated tools (Terraform, Cloudformation, etc.)

**Comment by dolfandringa** [comment] 2018-10-25 07:15
That is an option for static file storage indeed. Another option would be to use a CDN like cloudflare's or Amazon's CloudFront.

**Comment by Tim-Ho** [comment] 2018-10-25 09:04
> Yes, this kind of integration would be achieved through the use of boto3, most likely only "using" resources like existing S3 buckets, not managing their lifecycle (creation/destruction) as this would be quite out of scope of this project and better handled by dedicated tools (Terraform, Cloudformation, etc.)

Thanks so much .
You've been really helpful...
But there's other difficulty I've come across... 
How could I synchronize the path of the S3 with RDS(Mysql) Database 
so I can upload the path to my database and pull the path from the database and get the image from the path ?

**Comment by dolfandringa** [comment] 2018-10-26 06:37
I don't fully understand your question. Are talking file/image uploads like [described in the docs](https://flask-appbuilder.readthedocs.io/en/latest/quickfiles.html)? In that case the issue is that your app needs filesystem access to where you store your images. Having that on an S3 bucket would require extra work on your vm. I know it's possible to mount an S3 bucket as a normal filesystem under linux, so you could do that in your VM as well. See [this article](https://cloudkul.com/blog/mounting-s3-bucket-linux-ec2-instance/) about that.  I haven't really tried this though, so don't know how well this performs or how stable this is.

In flask appbuilder, the locations of images/files are governed by two configuration variables:
`IMG_UPLOAD_FOLDER` and `IMG_UPLOAD_URL`. See the [quick images example code](https://github.com/dpgaspar/Flask-AppBuilder/blob/master/examples/quickimages/config.py).
There you could set the right url/folder for your locally mounted S3 bucket and the url to your S3 bucket. 
If you mean by "upload the path of the S2 with RDS Database" you mean you want to store that configuration setting in your DB, that is a bit tricky, but might work maybe by creating a table/object in your datamodel to store those settings, including an appropriate view to add/edit those settings, and when you start your app, retrieve the settings from the db and update app.config with those values. You could then store IMG_UPLOAD_FOLDER and IMG_UPLOAD_URL in your database.

If you're purely talking about /static/ files (html/css/images of your static application), I would probably run your application [behind NGINX with uwsgi](https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-uwsgi-and-nginx-on-ubuntu-14-04) and configure the /static location there to redirect to your s3 bucket, or to [serve as a proxy to your bucket](https://stackoverflow.com/questions/44639182/nginx-proxy-amazon-s3-resources/44749584#44749584).

**Comment by Tim-Ho** [comment] 2018-10-26 17:43
thx so much

**Comment by dolfandringa** [comment] 2018-10-30 03:36
I am closing this issue to clean up our issue queue. But please feel free to re-open it if you want to discuss it further or have additional questions.

**Closed by dolfandringa** 2018-10-30 03:36 UTC
Labels: question

**Comment by Tim-Ho** [comment] 2018-11-17 09:53
> I am closing this issue to clean up our issue queue. But please feel free to re-open it if you want to discuss it further or have additional questions.

Hello! I have tried so hard to look for information through google , youtube and other search engine, but still cannot find the solution to it...
Could you please teach me how to achieve this ?
I really want to learn how to deploy flask appbuilder with S3
thx can you give me an example with appbuilder ...?
#####################################################
UPLOAD_FOLDER = basedir + '/app/static/uploads/'
IMG_UPLOAD_FOLDER = basedir + '/app/static/uploads/'
IMG_UPLOAD_URL = '/static/uploads/'
IMG_SIZE = (150,150,True)
AUTH_TYPE = 1
AUTH_ROLE_ADMIN = 'Admin'
AUTH_ROLE_PUBLIC = 'Public'
APP_NAME = "F.A.B. Example"
#####################################################
