### ISSUE TITLE
has_access decorator not applying permission

### ISSUE THREAD

**Issue by jvinolas** [dpgaspar/Flask-AppBuilder#172] opened 2015-05-23 23:25 UTC
I have this code inside a view:
```
	@action("NewTemplate","Create new Template","Are you sure?","fa-cube", single=True, multiple=False)
	@has_access
	def NewTemplate(self, item):
		....

	@expose('/start/<string:id>')
	@has_access	
	def start(self,id):
               ....
```
And it works as expected for action NewTemplate (that permission is being created), but the permission is not being created for start method. For what I can understand in api documentation (http://flask-appbuilder.readthedocs.org/en/latest/api.html) it should work also on expose methods, not only in actions.

The strange thing here is that the start permission is not being created (checked in frontend and in mysql database) but I get and Access denied message when trying to access start method (!!). I can't understand what I'm doing wrong.

**Comment by dpgaspar** [comment] 2015-05-23 23:52
This could be a bug... Your probably getting access denied because the is no permission inserted on the database. I'll try to reproduce the problem. Do you have errors on the log?

**Comment by dpgaspar** [comment] 2015-05-23 23:54
Just ran a quick test (using the quickhowto example, inserted your code on GroupModelView), and everything looks fine, do you have something like this on the log:

2015-05-24 00:51:48,035:INFO:flask_appbuilder.security.sqla.manager:Created Permission View: can start on GroupModelView
2015-05-24 00:51:48,161:INFO:flask_appbuilder.security.sqla.manager:Added Permission can start on GroupModelView to role Admin
2015-05-24 00:51:48,402:INFO:flask_appbuilder.security.sqla.manager:Created Permission View: can NewTemplate on GroupModelView
2015-05-24 00:51:48,535:INFO:flask_appbuilder.security.sqla.manager:Added Permission can NewTemplate on GroupModelView to role Admin
2015-05-24 00:51:48,775:INFO:flask_appbuilder.security.sqla.manager:Created Permission View: NewTemplate on GroupModelView
2015-05-24 00:51:48,890:INFO:flask_appbuilder.security.sqla.manager:Added Permission NewTemplate on GroupModelView to role Admin

**Comment by dpgaspar** [comment] 2015-06-22 10:59
I will close this @jvinolas. If you still have this issue fell free to reopen it.

**Closed by dpgaspar** 2015-06-22 10:59 UTC
Labels: question
