### ISSUE TITLE
Using Appbuilder to login via an Api

### ISSUE THREAD

**Issue by purplepixels** [dpgaspar/Flask-AppBuilder#191] opened 2015-07-18 11:19 UTC
Hi there, I'm pretty new to Appbuilder (love it by the way) and am using it to build an API system at my workplace.

One of the things they have asked that I do is to provide login functionality via this API to our LDAP backend.

I'm got two issues that I need to solve to resolve this.
1. How do i bind a service account to LDAP prior to FAB making connections to it. Our LDAP servers do not allow searching unless an account has been bound to them. This also affects normal web logins at the moment. 
2. How can I pass the api values into the security system in FAB so it then uses that to connect to LDAP and returns details back (login/fail/etc) to me ?

Thank you!

**Comment by dpgaspar** [comment] 2015-07-20 18:15
Thanks! 
Well question 1 is related to #186, i think the problem is almost solved and 1.4.4 will be soon released with a fix for this.

On question 2, FAB does not have this right now, but you can create you own API to login and expose it, i'll update with more details on this as soon as 1.4.4 is released.

**Comment by purplepixels** [comment] 2015-07-21 03:50
Great! Thank you for your quick reply :)

How do i expose the login login in FAB so I can access it directly ?

**Comment by purplepixels** [comment] 2015-07-23 06:43
Okay, great.

Thank you for the response. I've worked around the issues listed above by writing my own wrapped function for ldap.

Looking forward to the API for appbuilder. Cheers for the hard work.

**Comment by OverlordQ** [comment] 2016-05-12 20:57
Any info on this? Also finding the need to have a script interact with a AppBuilder app that requires it logging in.

**Comment by MichaelPereira** [comment] 2016-08-23 16:43
I was able to implemente an API login with the following code:
```python
from flask import jsonify, request
from flask.ext.login import current_user, login_user,

from app import global_app
from app.exceptions import Unauthorized
from app.utils.decorators import check_login

def api_login():
    if request.method == 'POST':
        username = request.json['user']
        password = request.json['password']

        user = global_app.appbuilder.sm.auth_user_db(username, password)
        if user:
            login_user(user)

    if not current_user.is_authenticated():
        raise Unauthorized('Not logged in')

    data = UserSchema().dump(current_user).data
    return jsonify(user=data)
```
`UserSchema` is a class that converts the SQLAlchemy model to json using [marshmallow](https://marshmallow.readthedocs.io/)

**Comment by GregSilverman** [comment] 2017-07-25 14:09
Michael,
Can you please provide more detail on this? Where, for example did you drop this into (in `flask_appbuilder/views.py`, I presume)? Also, what is the `global_app` imported from? I do not see this as part of flask-appbuilder?

Thanks in advance!

Greg--

**Comment by GregSilverman** [comment] 2017-07-27 14:54
Never mind. I got it working via AJAX now. For those interested, I dropped this in `security/views.py` right under the login method for the AuthDBView class:

    @expose('/login_api/', methods=['GET', 'POST'])
     def login(self):
        from flask.ext.login import current_user, login_user
        from flask import Session
        if request.method == 'POST':
            username = dict(request.form)['username'][0] # request.form['user']
            password = dict(request.form)['password'][0] # request.form['password']

            user = self.appbuilder.sm.auth_user_db(username, password)
            if user:
                login_user(user, remember=False)
             
        if not current_user.is_authenticated():
            http_return_code = 401
            response = make_response(jsonify({'message': 'Login Failed',
                                             'severity': 'critical'}), http_return_code)

        http_return_code = 201
        response = make_response(jsonify({'message': 'Login Success',
                                          'severity': 'info'}), http_return_code)

        # https://blog.miguelgrinberg.com/post/cookie-security-for-flask-applications
        s = Session()
        import uuid
        s['uid'] = uuid.uuid4()
        response.set_cookie('session_id', str(s['uid']))

        #print response.status
        #print response.headers
        #print response.get_data()

        return response

The two curl methods used for testing were:
`curl --data "username=gms&password=test123" http://0.0.0.0:5000/login_api/ -v`
`curl -v --cookie "session=XXX" http://0.0.0.0:5000/patientview/api/read -v`

where XXX is the value of the returned session cookie. 

I would LOVE to get this working with authentication tokens, so as to make this stateless, but that looks like a bit of work. Has anyone done this @dpgaspar?

**Comment by fordguo** [comment] 2018-10-31 09:41
you can use  flask-login to custom the request_loader

`@appbuilder.sm.lm.request_loader
def load_user_from_request(request):
    api_key = request.args.get('api_key', None)
    if api_key is None and request.headers.get('Authorization'):
        auth_header = request.headers.get('Authorization')
        api_key = auth_header.replace('ApiKey ', '', 1)
    if api_key is None:
        return None
    ak = appbuilder.session.query(MyUser).filter_by(api_key=api_key).one_or_none()
    if ak:
        return ak
    return None
`

**Closed** 2019-01-13 22:03 UTC
Labels: question

**Comment by kalimuthu123** [comment] 2019-09-11 11:54
Using Appbuilder to login via an Api  i am tried to use fab as backend for my ionic application anyone suggest me the way
